### ISSUE TITLE
SystemUiVisibility deprecated

### ISSUE THREAD

**Issue by AlleSchonWeg** [jamesmontemagno/MyCoffeeApp#14]
Hi @jamesmontemagno 
SystemUiVisibility is deprecated and i get a warning message:
https://github.com/jamesmontemagno/MyCoffeeApp/blob/af8d3704476668f9acac9b09ee76515cf11d1bb2/MyCoffeeApp/MyCoffeeApp.Android/MainActivity.cs#L66

Do you know a replacement for SystemUiVisibility ?

**Comment by jamesmontemagno** [comment]
Yup, so this was deprecated in R, but still totally works just fine, but you should be able to replace it with:

```csharp
var wic = new WindowInsetsControllerCompat(window, window.DecorView);

wic.AppearanceLightStatusBars = darkStatusBarTint; 
```

**Comment by jamesmontemagno** [comment]
Specifically I had to do this:

```csharp
public async void SetStatusBarColor(System.Drawing.Color color, bool darkStatusBarTint)
        {
            await Task.Delay(50); // a tiny little delay is needed when transitioning
            if (Build.VERSION.SdkInt < Android.OS.BuildVersionCodes.Lollipop)
                return;

            var activity = Platform.CurrentActivity;
            var window = activity.Window;

            //this may not be necessary(but may be fore older than M)
            window.AddFlags(Android.Views.WindowManagerFlags.DrawsSystemBarBackgrounds);
            window.ClearFlags(Android.Views.WindowManagerFlags.TranslucentStatus);
            

            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.M)
            {         

                var wic = new WindowInsetsControllerCompat(window, window.DecorView);              
                wic.AppearanceLightStatusBars = darkStatusBarTint;
            }

            window.SetStatusBarColor(color.ToPlatformColor());
        }
```

**Comment by AlleSchonWeg** [comment]
Thank you. Instead creating a new WindowInsetsControllerCompat, i modified your sample. This works for me:

```C#
WindowCompat.GetInsetsController(window, window.DecorView).AppearanceLightStatusBars = darkStatusBarTint;
```

**Comment by jamesmontemagno** [comment]
Nice! Yup that should work :) I'll update the code. I will see if this effects the await Task.Delay() I had to put in there.

**Comment by AlleSchonWeg** [comment]
Hi @jamesmontemagno ,
if you switch from light to dark via system settings and the app is in backround set `AppearanceLightStatusBars = false` will not work. From dark to light and set `AppearanceLightStatusBars = true` works. Do you have an idea why this is not working?
Thx

**Comment by jamesmontemagno** [comment]
All the code worked for me and in my apps.

I did have to add this small wait in it in -> https://github.com/jamesmontemagno/MyCoffeeApp/blob/master/MyCoffeeApp/MyCoffeeApp.Android/MainActivity.cs#L69

**Comment by AlleSchonWeg** [comment]
Hi @jamesmontemagno 
i found my bug. In my styles.xml i had set:

`<item name="android:windowLightStatusBar">true</item>`

After removed this line the code works. Also with no Task.Delay.

**Comment by AlleSchonWeg** [comment]
Hi @jamesmontemagno ,
another problem. ;) Without
`<item name="android:windowLightStatusBar">true</item>`
in the styles.xml files the SplashScreen is not working. Statusbar text is white (difficult to see):
![image](https://user-images.githubusercontent.com/6727366/163113597-d3aa4469-8604-48be-b143-e919b180eba6.png)
But with `<item name="android:windowLightStatusBar">true</item>`  the problem which i described here https://github.com/jamesmontemagno/MyCoffeeApp/issues/14#issuecomment-1054111311 occurs.
